### ISSUE TITLE
requests.py运行报错

### ISSUE THREAD

**Issue by Gaaraly** [bfdyanshe/onekeySchoolNetwork#1]
Traceback (most recent call last):
  File "C:/Users/Precious/Downloads/byRequsts.py", line 115, in <module>
    ip=GetIp()
  File "C:/Users/Precious/Downloads/byRequsts.py", line 40, in GetIp
    myIp=re.findall(r"ss5=\"(.+?)\"",str(bsobj))[0]
IndexError: list index out of range

**Comment by Gaaraly** [comment]
好像我多次重复登陆注销后，就成功了

**Comment by bfdyanshe** [comment]
额，这个大概率是已经登陆了的报错。偷懒就没有写错误提示。
